name: PR Verifier

permissions: {}

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  verify:
    name: verify PR contents
    uses: metal3-io/project-infra/.github/workflows/pr-verifier.yaml@main # zizmor: ignore[unpinned-uses]
